name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: ls -la dist

      - name: Deploy to gh-pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          git config --global user.email "o927416847@gmail.com"
          git config --global user.name "ttpss930141011"
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git fetch gh-token
          git checkout -b gh-pages
          git add -f dist
          git commit -m "Deploy to GitHub Pages"
          git push -f gh-token gh-pages:gh-pages
